name: redis-cluster

services:
  redis1:
    image: redis:7-alpine
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./redis.conf:/redis.conf
    environment:
      - CLUSTER_NODES=redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379
      - CLUSTER_REPLICAS=1
#       alternative with no replication
#      - CLUSTER_NODES=redis1:6379 redis2:6379 redis3:6379
#      - CLUSTER_REPLICAS=0
    depends_on:
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
      redis4:
        condition: service_healthy
      redis5:
        condition: service_healthy
      redis6:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis2:
    extends:
      file: redis-base.yml
      service: base-redis

  redis3:
    extends:
      file: redis-base.yml
      service: base-redis

  redis4:
    extends:
      file: redis-base.yml
      service: base-redis

  redis5:
    extends:
      file: redis-base.yml
      service: base-redis

  redis6:
    extends:
      file: redis-base.yml
      service: base-redis