services:
  redis_1:
    image: redis:7-alpine
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - CLUSTER_NODES=localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384 localhost:6385
      - CLUSTER_REPLICAS=1
      - REDIS_PORT=6380
    depends_on:
      redis_2:
        condition: service_healthy
      redis_3:
        condition: service_healthy
      redis_4:
        condition: service_healthy
      redis_5:
        condition: service_healthy
      redis_6:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    network_mode: host

  redis_2:
    extends:
      file: redis-base.yml
      service: base-redis
    command: redis-server /usr/local/etc/redis/redis.conf --port 6381 
    network_mode: host

  redis_3:
    extends:
      file: redis-base.yml
      service: base-redis
    command: redis-server /usr/local/etc/redis/redis.conf --port 6382 
    network_mode: host

  redis_4:
    extends:
      file: redis-base.yml
      service: base-redis
    command: redis-server /usr/local/etc/redis/redis.conf --port 6383 
    network_mode: host

  redis_5:
    extends:
      file: redis-base.yml
      service: base-redis
    command: redis-server /usr/local/etc/redis/redis.conf --port 6384 
    network_mode: host

  redis_6:
    extends:
      file: redis-base.yml
      service: base-redis
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --port 6385 
    network_mode: host
