name: redis-cluster-host

services:
  redis_1:
    image: redis:7-alpine
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./redis.conf:/redis.conf
    environment:
      - REDIS_PORT=6380
      # - CLUSTER_NODES=localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384 localhost:6385
      # - CLUSTER_REPLICAS=1
      # alternative with no replication
      - CLUSTER_NODES=localhost:6380 localhost:6381 localhost:6382
      - CLUSTER_REPLICAS=0
    depends_on:
      redis_2:
        condition: service_healthy
      redis_3:
        condition: service_healthy
      redis_4:
        condition: service_healthy
      redis_5:
        condition: service_healthy
      redis_6:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    healthcheck:
      test: redis-cli -p 6380 ping
      interval: 1s
      timeout: 3s
      retries: 30
    network_mode: host

  redis_2:
    extends:
      file: redis-base.yml
      service: base-redis
    network_mode: host
    command: redis-server /redis.conf --port 6381
    healthcheck:
      test: redis-cli -p 6381 ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis_3:
    extends:
      file: redis-base.yml
      service: base-redis
    network_mode: host
    command: redis-server /redis.conf --port 6382
    healthcheck:
      test: redis-cli -p 6382 ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis_4:
    extends:
      file: redis-base.yml
      service: base-redis
    network_mode: host
    command: redis-server /redis.conf --port 6383
    healthcheck:
      test: redis-cli -p 6383 ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis_5:
    extends:
      file: redis-base.yml
      service: base-redis
    network_mode: host
    command: redis-server /redis.conf --port 6384
    healthcheck:
      test: redis-cli -p 6384 ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis_6:
    extends:
      file: redis-base.yml
      service: base-redis
    environment:
      - REDIS_PORT=6385
    network_mode: host
    command: redis-server /redis.conf --port 6385
    healthcheck:
      test: redis-cli -p 6385 ping
      interval: 1s
      timeout: 3s
      retries: 30
