name: redis-laravel-benchmark

services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./redis_benchmark.php:/app/redis_benchmark.php
    depends_on:
      redis_1:
        condition: service_healthy
    command: /app/redis_benchmark.php cluster

  redis_1:
    image: redis:7-alpine
    hostname: redis_1
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./redis.conf:/redis.conf
    environment:
      - CLUSTER_NODES=redis_1:6379 redis_2:6379 redis_3:6379 redis_4:6379 redis_5:6379 redis_6:6379
      - CLUSTER_REPLICAS=1
      - REDIS_PORT=6379
    depends_on:
      redis_2:
        condition: service_healthy
      redis_3:
        condition: service_healthy
      redis_4:
        condition: service_healthy
      redis_5:
        condition: service_healthy
      redis_6:
        condition: service_healthy
    entrypoint: /entrypoint.sh
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis_2:
    extends:
      file: redis-base.yml
      service: base-redis
    hostname: redis_2

  redis_3:
    extends:
      file: redis-base.yml
      service: base-redis
    hostname: redis_3

  redis_4:
    extends:
      file: redis-base.yml
      service: base-redis
    hostname: redis_4

  redis_5:
    extends:
      file: redis-base.yml
      service: base-redis
    hostname: redis_5

  redis_6:
    extends:
      file: redis-base.yml
      service: base-redis
    hostname: redis_6
